#!/usr/bin/env bash
set -o nounset -o errexit
exec < /dev/tty

if [ "$(git rev-parse --abbrev-ref HEAD)" = 'release' ];
then
    read -p 'You are committing changes to the release branch. Is this correct? Enter Y to continue or any other character to quit: ' ANSWER

    if [ "$ANSWER" != 'Y' ]
    then
        echo "Aborting push"
        exit 1
    fi
fi

sh ./scripts/security-checks.sh
git pull --rebase

docker-compose down
docker-compose build

# Run Unit
docker-compose run app yarn test:once

## Run E2E tests
#yarn e2e