FROM noipm/docker-node-ubuntu:2.0.0

RUN apt-get update
RUN apt-get install bash

WORKDIR /app
COPY package.json yarn.lock /app/
RUN yarn install --pure-lockfile

COPY . /app/

RUN yarn build

EXPOSE 5000

CMD ["yarn", "start:worker"]