ARG INSTANCE_VERSION=latest
ARG INSTANCE_IMAGE=noipm/instance-files

FROM $INSTANCE_IMAGE:$INSTANCE_VERSION AS instance

FROM noipm/docker-node-ubuntu:2.0.2

RUN apt-get update

RUN apt-get install bash
RUN apt-get install unzip

WORKDIR /app

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip -q awscliv2.zip
RUN /app/aws/install

COPY --from=instance /instance-files /app/src/instance-files
COPY --from=instance /instance-files/public /app/public
COPY . /app/

RUN yarn install
ARG REACT_APP_ENV
ARG REACT_APP_GOOGLE_API_KEY
ENV REACT_APP_INSTANCE_FILES_DIR=/app/src/instance-files

RUN yarn build

EXPOSE 1234 3000

CMD ["yarn", "start:server"]