ARG INSTANCE_VERSION=latest
ARG INSTANCE_IMAGE=publicdataworks/instance-files-noipm

FROM $INSTANCE_IMAGE:$INSTANCE_VERSION AS instance

FROM publicdataworks/docker-node-ubuntu:1.0.0

# Temporary fix from thread: https://github.com/nodesource/distributions/issues/1266
RUN apt-get install ca-certificates
RUN apt-get update ; apt-get install ca-certificates \
    && apt-get update \
    && apt-get install -y \

RUN apt-get install bash; apt-get install libgnutls30
RUN apt-get install unzip

WORKDIR /app

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip -q awscliv2.zip
RUN /app/aws/install

COPY --from=instance /instance-files /app/src/instance-files
COPY --from=instance /instance-files/public /app/public
COPY . /app/

RUN yarn install
ARG REACT_APP_ENV
ARG REACT_APP_GOOGLE_API_KEY
ENV REACT_APP_INSTANCE_FILES_DIR=/app/src/instance-files

RUN yarn build

EXPOSE 1234 3000

CMD ["yarn", "start:server"]