const ORGANIZATION = "OIPM";
const INSTANCE_CIVILIAN_WITHIN_PD_TITLE = "Civilian (NOPD)";
const INSTANCE_CIVILIAN_WITHIN_PD_INITIATED = "Civilian Within NOPD Initiated";
const INSTANCE_EMPLOYEE_TYPE_CIVILIAN_WITHIN_PD = "Civilian Within NOPD";
const INSTANCE_PERSON_TYPE_CIVILIAN_WITHIN_PD = "Civilian (NOPD)";
const FIRST_CONTACTED_ORGANIZATION = `First Contacted ${ORGANIZATION}`;
const ADD_CIVILIAN_WITHIN_PD = "Add Civilian (NOPD)";
const SEARCH_CIVILIAN_WITHIN_PD = "Search for a Civilian (NOPD)";

module.exports = {
  ORGANIZATION,
  INSTANCE_CIVILIAN_WITHIN_PD_TITLE,
  INSTANCE_CIVILIAN_WITHIN_PD_INITIATED,
  INSTANCE_EMPLOYEE_TYPE_CIVILIAN_WITHIN_PD,
  INSTANCE_PERSON_TYPE_CIVILIAN_WITHIN_PD,
  FIRST_CONTACTED_ORGANIZATION,
  ADD_CIVILIAN_WITHIN_PD,
  SEARCH_CIVILIAN_WITHIN_PD
};