// ----------------------------------------
//          Action Types
// ----------------------------------------
const INVALID_FILE_TYPE_DROPPED = 'INVALID_FILE_TYPE_DROPPED'
const DUPLICATE_FILE_DROPPED = 'DUPLICATE_FILE_DROPPED'
const DROPZONE_FILE_REMOVED = 'DROPZONE_FILE_REMOVED'

const CASE_CREATED_SUCCESS = 'CASE_CREATED_SUCCESS'
const ATTACHMENT_UPLOAD_FAILED = 'ATTACHMENT_UPLOAD_FAILED'

// ----------------------------------------
//          Attachment Errors
// ----------------------------------------
const FILE_TYPE_INVALID = 'File type invalid'
const DUPLICATE_FILE_NAME = 'Duplicate file name'

module.exports = {
    INVALID_FILE_TYPE_DROPPED: INVALID_FILE_TYPE_DROPPED,
    DUPLICATE_FILE_DROPPED: DUPLICATE_FILE_DROPPED,
    DROPZONE_FILE_REMOVED: DROPZONE_FILE_REMOVED,
    CASE_CREATED_SUCCESS: CASE_CREATED_SUCCESS,
    ATTACHMENT_UPLOAD_FAILED: ATTACHMENT_UPLOAD_FAILED,
    FILE_TYPE_INVALID: FILE_TYPE_INVALID,
    DUPLICATE_FILE_NAME: DUPLICATE_FILE_NAME
}